[package]
name = "input-echoer"
version = "1.0.0"
authors = ["Ivan De Marino <detronizator@gmail.com>"]
description = "Echoes all input it receives (env-vars & args): useful during development"
edition = "2018"

[dependencies]
